cache:
  paths:
    - _build/
    - deps/
    - priv/plts/

image: elixir:latest

mix:
  script:
    - mkdir -p priv/plts
    - mix deps.clean --unused
    - mix deps.update --all
    - mix git_hooks.run all
